version: '3.9'

services:
  redis:
    image: redis:7.4.6
    container_name: pventure_redis
    ports:
      - "6379:6379"
    networks:
      - pventure_network

networks:
  pventure_network:
    driver: bridge
